import type { KanbanColumn } from "./kanban-types";

export const COLUMNS: KanbanColumn[] = [
  {
    key: "todo",
    label: "To Do",
    headerColor: "border-gray-4",
    dotColor: "bg-gray-4",
    tasks: [
      {
        id: "td1",
        title: "Finalize Q3 headcount forecast model",
        project: "Analytics",
        projectColor: "indigo",
        priority: "High",
        dueDate: "May 15",
        avatar: "/images/user/user-01.png",
        comments: 2,
        attachments: 1,
        subtasks: { done: 0, total: 4 },
      },
      {
        id: "td2",
        title: "Draft updated remote work policy section",
        project: "HR Policies",
        projectColor: "emerald",
        priority: "Medium",
        dueDate: "May 18",
        avatar: "/images/user/user-02.png",
        comments: 0,
        attachments: 2,
      },
      {
        id: "td3",
        title: "Design interview scorecard template",
        project: "Recruitment",
        projectColor: "violet",
        priority: "Medium",
        dueDate: "May 20",
        avatar: "/images/user/user-03.png",
        comments: 1,
        attachments: 0,
      },
      {
        id: "td4",
        title: "Research new LMS vendors for compliance training",
        project: "Compliance",
        projectColor: "rose",
        priority: "Low",
        dueDate: "May 22",
        avatar: "/images/user/user-04.png",
        comments: 3,
        attachments: 1,
      },
    ],
  },
  {
    key: "inprogress",
    label: "In Progress",
    headerColor: "border-primary-600",
    dotColor: "bg-primary-600",
    tasks: [
      {
        id: "ip1",
        title: "Build onboarding automation workflow",
        project: "Onboarding",
        projectColor: "emerald",
        priority: "High",
        dueDate: "May 12",
        avatar: "/images/user/user-05.png",
        comments: 8,
        attachments: 3,
        subtasks: { done: 3, total: 6 },
      },
      {
        id: "ip2",
        title: "Review JDs for 3 Engineering roles",
        project: "Recruitment",
        projectColor: "violet",
        priority: "High",
        dueDate: "May 9",
        overdue: true,
        avatar: "/images/user/user-06.png",
        comments: 4,
        attachments: 2,
      },
      {
        id: "ip3",
        title: "Migrate employee records to new HRMS",
        project: "HRMS Migration",
        projectColor: "sky",
        priority: "High",
        dueDate: "May 14",
        avatar: "/images/user/user-07.png",
        comments: 6,
        attachments: 5,
        subtasks: { done: 2, total: 8 },
      },
      {
        id: "ip4",
        title: "Create Q2 benefits enrollment comms",
        project: "Benefits",
        projectColor: "amber",
        priority: "Medium",
        dueDate: "May 13",
        avatar: "/images/user/user-08.png",
        comments: 2,
        attachments: 1,
      },
      {
        id: "ip5",
        title: "Analyze attrition data for Engineering dept",
        project: "Analytics",
        projectColor: "indigo",
        priority: "Medium",
        dueDate: "May 16",
        avatar: "/images/user/user-09.png",
        comments: 1,
        attachments: 2,
        subtasks: { done: 1, total: 3 },
      },
    ],
  },
  {
    key: "review",
    label: "Review",
    headerColor: "border-amber-dark",
    dotColor: "bg-amber-dark",
    tasks: [
      {
        id: "rv1",
        title: "Employee handbook 2026 full draft",
        project: "HR Policies",
        projectColor: "emerald",
        priority: "High",
        dueDate: "May 10",
        overdue: true,
        avatar: "/images/user/user-10.png",
        comments: 12,
        attachments: 4,
        subtasks: { done: 5, total: 6 },
      },
      {
        id: "rv2",
        title: "Compensation benchmarking report",
        project: "Benefits",
        projectColor: "amber",
        priority: "High",
        dueDate: "May 11",
        avatar: "/images/user/user-11.png",
        comments: 5,
        attachments: 2,
      },
      {
        id: "rv3",
        title: "New hire offer letter templates",
        project: "Recruitment",
        projectColor: "violet",
        priority: "Medium",
        dueDate: "May 14",
        avatar: "/images/user/user-12.png",
        comments: 3,
        attachments: 1,
      },
      {
        id: "rv4",
        title: "Data privacy audit for HRMS migration",
        project: "Compliance",
        projectColor: "rose",
        priority: "High",
        dueDate: "May 15",
        avatar: "/images/user/user-01.png",
        comments: 7,
        attachments: 6,
        subtasks: { done: 3, total: 4 },
      },
    ],
  },
  {
    key: "done",
    label: "Done",
    headerColor: "border-emerald-dark",
    dotColor: "bg-emerald-dark",
    tasks: [
      {
        id: "dn1",
        title: "Q1 performance review cycle close-out",
        project: "Performance",
        projectColor: "indigo",
        priority: "High",
        dueDate: "Apr 30",
        avatar: "/images/user/user-02.png",
        comments: 4,
        attachments: 2,
      },
      {
        id: "dn2",
        title: "Compliance training Q2 rollout",
        project: "Compliance",
        projectColor: "rose",
        priority: "High",
        dueDate: "Apr 28",
        avatar: "/images/user/user-03.png",
        comments: 9,
        attachments: 3,
        subtasks: { done: 8, total: 8 },
      },
      {
        id: "dn3",
        title: "April payroll reconciliation",
        project: "Benefits",
        projectColor: "amber",
        priority: "High",
        dueDate: "May 2",
        avatar: "/images/user/user-04.png",
        comments: 2,
        attachments: 5,
      },
      {
        id: "dn4",
        title: "Publish internal job postings — May batch",
        project: "Recruitment",
        projectColor: "violet",
        priority: "Medium",
        dueDate: "May 1",
        avatar: "/images/user/user-05.png",
        comments: 1,
        attachments: 1,
      },
    ],
  },
];
